### ISSUE TITLE
Console Commands

### ISSUE THREAD

**Issue by AlexiWolf** [AlexiWolf/JoinCommands#3]
# Overview

## Purpose

Some commands may require elevated permissions, or are meant to be run by the server console.  Currently, there is no way of running these commands because it is only possible to run commands the player has permission to run.  A more advanced command config is required to address this limitation.

## Goals

  - Run commands as either the player or the server console.
  
# Proposed Solution

## Command Config Changes

Commands are still stored as a list of strings, but they now have a `run_as` value attached to them.  Commands can be run as the `player`,  or the `server_console`.  If no `run_as` value is provided, the command is ran as the player.

```yaml
new_player_commands:
  'player_command <arguments>':
    run_as: player
  'console_command <arguments>':
    run_as: server_console
```

## Command Runner Changes

Instead of being stored as Strings, commands are read from the config as a `JoinCommand`.  Depending on the configured `run_as` value, the `JoinCommand` class is responsible for running the command in whatever method is specified.
